services:
  postgres-dev:
    image: "postgres:15.7"
    environment:
      - POSTGRES_DB=$DB_NAME
      - POSTGRES_USER=$DB_USER
      - POSTGRES_PASSWORD=$DB_PASSWORD
      - POSTGRES_SCHEMA=$DB_SCHEMA
      - DB_ENV=dev
    ports:
      - "5432:5432"

  postgres-test:
    image: "postgres:15.7"
    environment:
      - POSTGRES_DB=$DB_NAME
      - POSTGRES_USER=$DB_USER
      - POSTGRES_PASSWORD=$DB_PASSWORD
      - POSTGRES_SCHEMA=$DB_SCHEMA
      - DB_ENV=test
    ports:
      - "5433:5432"
    expose:
      - "3000"

  app:
    build: .
    environment:
      - DB_HOST=postgres-dev
      - DB_NAME=$DB_NAME
      - DB_USER=$DB_USER
      - DB_PASSWORD=$DB_PASSWORD
      - DB_SCHEMA=$DB_SCHEMA
      - DB_PORT=5432
      - DB_ENV=dev
      - API_SECRET_KEY=random-secret-key-here
      - SESSION_SECRET_KEY=another-random-secret-key-here
      - PROCONNECT_CLIENT_ID=foo
      - PROCONNECT_CLIENT_SECRET=bar
      - PROCONNECT_URL_DISCOVER=foo
      - PROCONNECT_REDIRECT_URI=bar
      - PROCONNECT_POST_LOGOUT_REDIRECT_URI=foo
    depends_on:
      - postgres-dev

  nginx:
    image: "nginx:alpine-slim"
    ports:
      - "80:80"
    depends_on:
      - app
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
