services:
  postgres-local:
    image: "postgres:15.7"
    environment:
      - POSTGRES_DB=$DB_NAME
      - POSTGRES_USER=$DB_USER
      - POSTGRES_PASSWORD=$DB_PASSWORD
      - POSTGRES_SCHEMA=$DB_SCHEMA
      - DB_ENV=local
    ports:
      - "5432:5432"

  postgres-test:
    image: "postgres:15.7"
    environment:
      - POSTGRES_DB=$DB_NAME
      - POSTGRES_USER=$DB_USER
      - POSTGRES_PASSWORD=$DB_PASSWORD
      - POSTGRES_SCHEMA=$DB_SCHEMA
      - DB_ENV=test
    ports:
      - "5433:5432"
    expose:
      - "3000"

  app:
    build: .
    environment:
      - DB_HOST=postgres-local
      - DB_NAME=$DB_NAME
      - DB_USER=$DB_USER
      - DB_PASSWORD=$DB_PASSWORD
      - DB_SCHEMA=$DB_SCHEMA
      - DB_PORT=5432
      - DB_ENV=local
    depends_on:
      - postgres-local

  nginx:
    image: "nginx:alpine-slim"
    ports:
      - "80:80"
    depends_on:
      - app
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
