services:
  postgres-dev:
    image: "postgres:15.7"
    build: .
    environment:
      - POSTGRES_DB=$DB_NAME
      - POSTGRES_USER=$DB_USER
      - POSTGRES_PASSWORD=$DB_PASSWORD
      - POSTGRES_SCHEMA=$DB_SCHEMA
      - DB_ENV=dev
    ports:
      - "5432:5432"

  postgres-test:
    image: "postgres:15.7"
    build: .
    environment:
      - POSTGRES_DB=$DB_NAME
      - POSTGRES_USER=$DB_USER
      - POSTGRES_PASSWORD=$DB_PASSWORD
      - POSTGRES_SCHEMA=$DB_SCHEMA
      - DB_ENV=test
    ports:
      - "5433:5432"
