services:
  postgres-dev:
    image: "postgres:15.7"
    volumes:
      - ./db/migrate/:/docker-entrypoint-initdb.d/
    environment:
      - POSTGRES_DB=d-roles
      - POSTGRES_USER=d-roles
      - POSTGRES_PASSWORD=d-roles
      - POSTGRES_SCHEMA=d_roles
    ports:
      - "5432:5432"
