services:
  postgres-dev:
    image: "postgres:15.7"
    volumes:
      # - ./db/migrations/dev:/docker-entrypoint-initdb.d/
      - ./db/initdb/schema.sql:/docker-entrypoint-initdb.d/000000-schema.sql
      - ./db/seeds/dev/seed.sql:/docker-entrypoint-initdb.d/999999-seed.sql
    environment:
      - POSTGRES_DB=d-roles
      - POSTGRES_USER=d-roles
      - POSTGRES_PASSWORD=d-roles
      - POSTGRES_SCHEMA=d_roles
    ports:
      - "5432:5432"

  postgres-test:
    image: "postgres:15.7"
    volumes:
      # - ./db/migrations/dev:/docker-entrypoint-initdb.d/
      - ./db/initdb/schema.sql:/docker-entrypoint-initdb.d/000000-schema.sql
      - ./db/seeds/test/seed.sql:/docker-entrypoint-initdb.d/999999-seed.sql
    environment:
      - POSTGRES_DB=d-roles-test
      - POSTGRES_USER=d-roles
      - POSTGRES_PASSWORD=d-roles
      - POSTGRES_SCHEMA=d_roles
    ports:
      - "5433:5432"
