name: Docker Compose Test

on:
  pull_request:
    branches: [ main ]

jobs:
  docker-compose-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Create .env file
      run: |
        cat > .env << EOF
        DB_NAME=d-roles
        DB_USER=d-roles
        DB_PASSWORD=d-roles
        DB_SCHEMA=d_roles

    - name: Build and start services
      run: make docker

    - name: Wait for services to be ready
      run: |
        echo "Waiting for app to be ready..."
        timeout 3m bash -c 'until curl -f http://localhost:80/health; do sleep 2; done'

    - name: Run health checks
      run: |
        # Test postgres connection
        docker-compose exec -T postgres-local psql -U d-roles -d d-roles -c "SELECT hey FROM d_roles.group_service_provider_relations;"

        # Test app health endpoint
        curl -f http://localhost/health/

    - name: Cleanup
      if: always()
      run: docker-compose down -v
